project_id = "orezkovqdxudgsvqrtoi"

[functions.generate-horoscope]
verify_jwt = true

[functions.generate-natal-chart-analysis]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-daily-horoscope]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false

[functions.generate-compatibility]
verify_jwt = true

[functions.generate-transits-analysis]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.custom-auth-email]
verify_jwt = false

[functions.generate-personal-forecast]
verify_jwt = true
