project_id = "orezkovqdxudgsvqrtoi"

[functions.generate-horoscope]
verify_jwt = true

[functions.generate-natal-chart-analysis]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-daily-horoscope]
verify_jwt = false
